
n_g:
  desc: Number of g blocks
  value: 9
n_g_k:
  desc: Number of g subblocks 
  value: 3
x_noise:
  desc: Magnitude of noise added to points
  value: 0.0001
n_epochs:
  desc: Number of epochs to train for
  value: 2000
random_dataloader:
  desc: Use random dataloader
  value: True
sample_size:
  desc: Number of points sampled from clouds
  value: 2048
categories:
  desc: Categories to use for shapenet
  value: ['airplane']
data_root_dir:
  desc: Root dir of data folder for shapenet
  value: data//ShapeNetCore.v2.PC15k
batch_size:
  desc: Batch size
  value: 1 # Should be 50 ?
lr:
  desc: Initial learning rate for optimizer
  value: 0.00001 # Original 0.0001
save_model_path:
  desc: Where to save models (before wandb upload)
  value: save/straight




