sample_size:
  desc: Max number of points
  value: 2000
n_flow_layers:
  desc: Number of flow layers
  value: 25
data_loader:
  desc: What loader to use
  value: ConditionalDataGridCircle
batchnorm:
  desc: batchnorm between flow layers
  value: false
flow_type:
  desc: What flow blocks to use
  value: exponential_coupling
hidden_dims:
  desc: linear layers for flow coupling
  value: [512,512,512,512,512,512]
permuter_type:
  desc: 'How to permute between coupling blocks'
  value: random_permute
early_stop_margin:
  desc: early_stop_margin
  value: 0.0003
count_bins:
  desc: bins for spline
  value: 64
input_dim:
  desc: Dimension of pointcloud data
  value: 6
grid_square_size:
  desc: grid_square_size
  value: 2
clearance:
  desc: clearance
  value: 10
subsample:
  desc: How to subsample
  value: 'fps'
patience:
  desc: patience
  value: 150
preload:
  desc: Preload_dataset
  value: true
min_points:
  desc: Minimum sample size
  value: 2000
min_lr:
  desc: Minimum schedules learning rate
  value: 0.00005
n_epochs:
  desc: Number of epochs to train for
  value: 10000
context_dim:
  desc: Dimension of embedding w (encoder output) ,e (conditioner)
  value: 600
batch_size:
  desc: Batch size
  value: 25 #35
lr:
  desc: Initial learning rate for optimizer
  value: 0.0005
save_model_path:
  desc: Where to save models (before wandb upload)
  value: save/conditional_flow_compare/
num_workers:
  desc: num_workers
  value: 2
optimizer_type:
  desc: optimizer type
  value: AdamW
batchnorm_encodings:
  desc: batchnorm after output of encoder
  value: false
encoder_type:
  desc: What pointcloud encoder to use
  value: gcn
weight_decay:
  desc: weigth decay for optimizer
  value: 0.001
data_parallel:
  desc: Use parallel
  value: false
normalization:
  desc: How pairs are normalized
  value: co_unit_sphere
preselected_points:
  desc: Use preselected points
  value: true
dirs_challenge_csv:
  desc: Paths to label csv folder
  value: save/2016-2020-train/
load_checkpoint:
  desc: path to save checkpoint or false
  value: save/conditional_flow_compare/sandy-elevator-1193_3_112_model_dict.pt