batch_size:
  desc: Batch size for post_clasification training
  value: 16
dropout:
  desc: Dropout value for gcn
  value: 0.2
lr:
  desc: Learning rate
  value: 0.0001
k:
  desc: N neighbours for gcn
  value: 60
weight_decay:
  desc: weigth decay for optimizer (l1 reg)
  value: 0.001
n_epochs:
  desc: Number of epochs to train for
  value: 100
keep_rgb:
  desc: Include rgb chanels
  value: false
merge_classes:
  desc: Only have change nochange
  value: true

