sample_size:
  desc: Max number of points
  value: 2048 #2048
n_flow_layers:
  desc: Number of flow layers
  value: 115 # was 46 for 64 latent
data_loader:
  desc: What loader to use
  value: AmsGridLoader #AmsGridLoader
flow_type:
  desc: What flow blocks to use
  value:  AffineCoupling #RationalQuadraticSplineCoupling #AffineCoupling
hidden_dims:
  desc: linear layers for flow coupling
  value: [512,512,512] # was [512,512,512]
hidden_dims_embedder_out:
  desc: Hidden dims on embedder output mlp
  value: [512,512,512,512,512,512] # was [512,512,512]
permuter_type:
  desc: 'How to permute between coupling blocks'
  value: LinearLU #ExponentialCombiner #FullCombiner # ExponentialCombiner # random_permute, LinearLU 
early_stop_margin:
  desc: early_stop_margin
  value: 0.0003
input_dim:
  desc: Dimension of pointcloud data
  value: 6
grid_square_size:
  desc: Size of grid square or circle diameter
  value: 2 # was 2 !!!
clearance:
  desc: clearance
  value: 10
subsample:
  desc: How to subsample
  value: 'fps'
patience:
  desc: patience (number of batches not epochs!)
  value: 1000 #Was 10 for challenge
preload:
  desc: Preload_dataset
  value: true
min_points:
  desc: Minimum sample size
  value: 2000
n_epochs:
  desc: Number of epochs to train for
  value: 2000
batch_size:
  desc: Batch size
  value: 12  #16
lr:
  desc: Initial learning rate for optimizer
  value: 1.0E-4 # was  1.0E-4
save_model_path:
  desc: Where to save models (before wandb upload)
  value: save/conditional_flow_compare/
num_workers:
  desc: num_workers
  value: 4
optimizer_type:
  desc: optimizer type
  value: Adam #was Adam
weight_decay:
  desc: weigth decay for optimizer (l1 reg)
  value: 0.0 #was 0.000001 Affects bits per dim
data_parallel:
  desc: Use parallel
  value: false
coupling_block_nonlinearity:
  desc: coupling_block_nonlinearity
  value: GELU
min_lr:
  desc: Minimum schedules learning rate
  value: 1.0E-8
normalization:
  desc: How pairs are normalized
  value: co_unit_sphere
load_checkpoint:
  desc: Path to checkpoint or false for new training
  value: false
preselected_points:
  desc: Use preselected points
  value: true
dirs_challenge_csv:
  desc: Paths to label csv folder
  value: save/2016-2020-train/
attn_dim:
  desc: Dimension of cross attention embedding fed to coupling block MLP (dim of latent output of attention block)
  value: 512
latent_dim:
  desc: Latent dim for main flow - output of first augment
  value: 300
attn_input_dim:
  desc: dim of input to attn
  value: 256
input_embedding_dim:
  desc: Dimension of input embeddings, part of input for attention (feature dim for each point in cloud t0)
  value: 64
cross_heads:
  desc: Number of attn heads
  value: 1
cross_dim_head:
  desc: Dimension of cross dim head
  value: 256 #64
attn_dropout:
  desc: Dropout rate in attn module
  value: 0.0
amp:
  desc: Automatic mixed precision
  value: false
input_embedder: 
  desc: input_embedder type
  value: DGCNNembedder
grad_clip_val:
  desc: What value to clip grad norms to
  value: 1.0 # was 1.0
batches_per_sample:
  desc: Every how many batches to create a sample
  value: 15
batches_per_save:
  desc: Every how many batches to create a sample
  value: 1000 
n_neighbors:
  desc: N neighbors for gcn knn aggregation steps
  value: 40
eps_expm:
  desc: Precision for computation of matrix exponential
  value: 1.0E-8 # Was 1.0E-8
augmenter_dist:
  desc: What dist to use for first augmenter
  value: StandardNormal # ConditionalMeanStdNormal #ConditionalNormal, StandardUniform
net_augmenter_dist_hidden_dims: 
  desc: Net hidden sizes for initial augmenter dim if using conditional distribution
  value: [128,128,128] #Not being used 
pre_attention_mlp_hidden_dims:
  desc: Hidden dims for pre attention mlp
  value: [256,256,256] # was # 64 64 64 64
n_flows_cif:
  desc: Number of flows in each cif block between augment and slice
  value : 1 
cif_dist:
  desc: What dist to use for augment/slice in cif blocks
  value: ConditionalNormal
net_cif_dist_hidden_dims:
  desc: Hidden dims for conditional distribution nets in the cif augmenter/slicer
  value: [64,64]
cif_latent_dim:
  desc: Latent dim in flow of cif blocks
  value: 300
coupling_expm_algo:
  desc: What algorithm to use for expm 'original' or 'torch'
  value: torch # Was original
act_norm:
  desc: Include act norm in main flow 
  value: true 
cif_act_norm:
  desc: Include act norm in CIF block flows 
  value: true
make_samples:
  desc: Make samples during training
  value: true
clamp_dist:
  desc: Clamp std val for stability
  value: 10.0
time_stats:
  desc: Use cuda synchronize to get time stats
  value: false
conditional_aug_cif:
  desc: Use conditional info in augment of cif
  value: True
conditional_slice_cif:
  desc: Use conditional info in slice of cif
  value: True
num_bins_spline:
  desc: How many bins to use for spline flow
  value: 8 # 128
linear_lu_eps:
  desc: Eps used for linear lu combiner
  value: 1.0E-5
threshold_scheduler:
  desc: Threshold to change lr at for scheduler
  value: 0.01 #Percentage
lr_factor:
  desc: Multiplication factor for lr scheduler]
  value: 0.8
mem_iter_scheduler:
  desc: Every how many batches to reset and adjust custom scheduler
  value: 800
lr_scheduler:
  desc: What scheduler to use
  value: custom
affine_scale_fn:
  desc: Scaling function to use for affine coupling
  value: sigmoid




