sample_size:
  desc: Max number of points
  value: 2000
n_flow_layers:
  desc: Number of flow layers
  value: 30
data_loader:
  desc: What loader to use
  value: ConditionalDataGridCircle
batchnorm:
  desc: batchnorm between flow layers
  value: false
flow_type:
  desc: What flow blocks to use
  value: exponential_coupling
hidden_dims:
  desc: linear layers for flow coupling
  value: [512,512,512]
permuter_type:
  desc: 'How to permute between coupling blocks'
  value: Exponential_combiner
early_stop_margin:
  desc: early_stop_margin
  value: 0.0003
input_dim:
  desc: Dimension of pointcloud data
  value: 6
grid_square_size:
  desc: Number of f subblocks 
  value: 2
clearance:
  desc: clearance
  value: 28
subsample:
  desc: How to subsample
  value: 'fps'
patience:
  desc: patience
  value: 10
preload:
  desc: Preload_dataset
  value: true
min_points:
  desc: Minimum sample size
  value: 2000
n_epochs:
  desc: Number of epochs to train for
  value: 2000
batch_size:
  desc: Batch size
  value: 16 #35
lr:
  desc: Initial learning rate for optimizer
  value: 0.00001
save_model_path:
  desc: Where to save models (before wandb upload)
  value: save/conditional_flow_compare/
num_workers:
  desc: num_workers
  value: 4
optimizer_type:
  desc: optimizer type
  value: Adam
weight_decay:
  desc: weigth decay for optimizer (l1 reg)
  value: 0.0
data_parallel:
  desc: Use parallel
  value: false
coupling_block_nonlinearity:
  desc: coupling_block_nonlinearity
  value: ELU
min_lr:
  desc: Minimum schedules learning rate
  value: 0.000005
normalization:
  desc: How pairs are normalized
  value: co_unit_sphere
load_checkpoint:
  desc: Path to checkpoint or false for new training
  value: false
preselected_points:
  desc: Use preselected points
  value: true
dirs_challenge_csv:
  desc: Paths to label csv folder
  value: save/2016-2020-train/
attn_dim:
  desc: Dimension of cross attention embedding fed to coupling block MLP (dim of latent output of attention block)
  value: 512
latent_dim:
  desc: Dimension of flow input, result of mlp blowup
  value: 6
attn_input_dim:
  desc: dim of input to attn
  value: 124
input_embedding_dim:
  desc: Dimension of input embeddings, part of input for attention (feature dim for each point in cloud t0)
  value: 256
cross_heads:
  desc: Number of attn heads
  value: 1
cross_dim_head:
  desc: Dimension of cross dim head
  value: 256 #64
attn_dropout:
  desc: Dropout rate in attn module
  value: 0.0
amp:
  desc: Automatic mixed precision
  value: true
lr_scheduler:
  desc: Type of lr scheduling
  value: ReduceLROnPlateau
input_embedder:
  desc: input_embedder type
  value: DGCNNembedder
attention_frequency:
  desc: flow is attented if index % attention frequency == 0 
  value: 1
attn_connection:
  desc: pass attention between blocks
  value: true
grad_clip_val:
  desc: What value to clip grad norms to
  value: 2.0