sample_size:
  desc: Max number of points
  value: 10000
n_flow_layers:
  desc: Number of flow layers
  value: 15
data_loader:
  desc: What loader to use
  value: ChallengeDataset
batchnorm:
  desc: batchnorm between flow layers
  value: false
flow_type:
  desc: What flow blocks to use
  value: exponential_coupling
hidden_dims:
  desc: linear layers for flow coupling
  value: [512,512,512]
permuter_type:
  desc: 'How to permute between coupling blocks'
  value: random_permute
early_stop_margin:
  desc: early_stop_margin
  value: 0.01
count_bins:
  desc: bins for spline
  value: 64
input_dim:
  desc: Dimension of pointcloud data
  value: 6
grid_square_size:
  desc: Number of f subblocks 
  value: 4
radius:
  desc: Radius for challenge dataset
  value: 2
clearance:
  desc: clearance
  value: 20
subsample:
  desc: How to subsample
  value: 'random'
patience:
  desc: patience
  value: 50
preload:
  desc: Preload_dataset
  value: false
min_points:
  desc: Minimum sample size
  value: 2000
n_epochs:
  desc: Number of epochs to train for
  value: 2500
batch_size:
  desc: Batch size
  value: 1 #35
lr:
  desc: Initial learning rate for optimizer
  value: 0.0001
save_model_path:
  desc: Where to save models (before wandb upload)
  value: save/straight_flow_compare/
num_workers:
  desc: num_workers
  value: 2
optimizer_type:
  desc: optimizer type
  value: AdamW
weight_decay:
  desc: weigth decay for optimizer
  value: 0.0001
data_parallel:
  desc: Use parallel
  value: true
coupling_block_nonlinearity:
  desc: coupling_block_nonlinearity
  value: ELU
min_lr:
  desc: Minimum scheduled learning rate
  value: 0.00005
normalization:
  desc: How pairs are normalized
  value: min_max
load_checkpoint:
  desc: Path to checkpoint or false for new training
  value: false
dir_challenge:
  desc: Paths to folders in order of year
  value: save/challenge_data/Shrec_change_detection_dataset_public/
dirs_challenge_csv:
  desc: Paths to label csv folder
  value: save/2016-2020-train/
patience_stopper:
  desc: Patience of early stopper
  value: 50
reinitialize_before_reverse:
  desc: Reset parameters before reverse
  value: false
points_per_batch:
  desc: Points per batch
  value: 200
remove_ground:
  desc: Remove ground
  value: true

