sample_size:
  desc: Max number of points
  value: 2000
n_flow_layers:
  desc: Number of flow layers
  value: 10
batchnorm:
  desc: batchnorm between flow layers
  value: true
flow_type:
  desc: What flow blocks to use
  value: exponential_coupling
hidden_dims:
  desc: linear layers for flow coupling
  value: [400,400,400]
permuter_type:
  desc: 'How to permute between coupling blocks'
  value: random_permute
scaler_type:
  desc: How to scale after permute
  value: Sigmoid_scaler
early_stop_margin:
  desc: early_stop_margin
  value: 0.0003
count_bins:
  desc: bins for spline
  value: 64
input_dim:
  desc: Dimension of pointcloud data
  value: 6
grid_square_size:
  desc: Number of f subblocks 
  value: 4
clearance:
  desc: clearance
  value: 10
subsample:
  desc: How to subsample
  value: 'random'
patience:
  desc: patience
  value: 50
preload:
  desc: Preload_dataset
  value: True
min_points:
  desc: Minimum sample size
  value: 2000
n_epochs:
  desc: Number of epochs to train for
  value: 3000
context_dim:
  desc: Dimension of embedding w (encoder output) ,e (conditioner)
  value: 32
batch_size:
  desc: Batch size
  value: 20
lr:
  desc: Initial learning rate for optimizer
  value: 0.001
save_model_path:
  desc: Where to save models (before wandb upload)
  value: save/conditional_flow_compare/
num_workers:
  desc: num_workers
  value: 8
optimizer_type:
  desc: optimizer type
  value: AdamW
batchnorm_encodings:
  desc: batchnorm after output of encoder\
  value: true
encoder_type:
  desc: What pointcloud encoder to use
  value: gcn