
n_f:
  desc: Number of f blocks
  value: 8
n_f_k:
  desc: Number of f subblocks 
  value: 3
n_g:
  desc: Number of g blocks
  value: 3
n_g_k:
  desc: Number of g subblocks
  value: 2
x_noise:
  desc: Magnitude of noise added to points
  value: 0.0001
n_epochs:
  desc: Number of epochs to train for
  value: 3000
random_dataloader:
  desc: Use random dataloader
  value: True
emb_dim:
  desc: Dimension of embedding w (encoder output) ,e (conditioner)
  value: 32
sample_size:
  desc: Number of points sampled from clouds
  value: 1000
categories:
  desc: Categories to use for shapenet
  value: ['airplane']
data_root_dir:
  desc: Root dir of data folder for shapenet
  value: data//ShapeNetCore.v2.PC15k
batch_size:
  desc: Batch size
  value: 2 # Should be 50 ?
lr:
  desc: Initial learning rate for optimizer
  value: 0.0001
save_model_path:
  desc: Where to save models (before wandb upload)
  value: save/straight_with_pointnet/




